[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql+asyncpg://eidolon_agent_memory:eidolon_agent_memory@localhost:25433/eidolon_agent_memory
